services:
  traefik:
    image: traefik:v3.2
    command: --api.insecure=true --providers.swarm
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo1:
    image: mongo
    hostname: mongo1
    restart: unless-stopped
    volumes:
      - nestjs_mongo_data1:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nestjs
      - MONGO_INITDB_ROOT_PASSWORD=supersecret

  gateway:
    image: yasc-gateway
    command: ["/app/dist/apps/gateway/main.js"]
    restart: unless-stopped
    env_file:
      - .env.production
    deploy:
      labels:
        - traefik.http.routers.yasc-gateway.rule=Host(`gateway.localhost`)
        - traefik.http.services.yasc-gateway.loadbalancer.server.port=3000

  users:
    image: yasc-users
    hostname: users
    command: ["/app/dist/apps/users/main.js"]
    restart: unless-stopped
    env_file:
      - .env.production
    deploy:
      labels:
        - traefik.http.routers.yasc-users.rule=Host(`users.localhost`)
        - traefik.http.services.yasc-users.loadbalancer.server.port=3001

volumes:
  nestjs_mongo_data1:
    name: nestjs_mongo_data1
  cassandra_data: